before_install:
  - brew unlink xctool
  - brew update
  - brew install xctool
language: objective-c
script:
  - xctool -workspace "Lighter Table View/Lighter Table View.xcworkspace" scheme "Lighter Table View" -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
  - xctool test -workspace "Lighter Table View/Lighter Table View.xcworkspace" scheme "Lighter Table View" -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
